import "server-only";

import { createAdminClient } from "@/lib/supabase/admin";

export const AI_PLATFORMS = ["instagram", "linkedin", "x", "facebook", "threads", "tiktok", "youtube"] as const;
export type AiPlatform = (typeof AI_PLATFORMS)[number];

const PLATFORM_RULES: Record<AiPlatform, { limit: number; titleLimit?: number; tone: string; format: string }> = {
  instagram: { limit: 2200, tone: "visual, conversational, concise", format: "caption with a strong opening, short paragraphs, relevant hashtags, and CTA" },
  linkedin: { limit: 3000, tone: "professional, useful, credible", format: "hook, useful context, concise body, practical takeaway, CTA; avoid engagement bait" },
  x: { limit: 280, tone: "sharp, concise, conversational", format: "one compact post with a clear idea and optional CTA; hashtags only when useful" },
  facebook: { limit: 63206, tone: "friendly, accessible, community-oriented", format: "readable post with context and a natural CTA" },
  threads: { limit: 500, tone: "casual, conversational, human", format: "short text-first post with a clear thought and optional CTA" },
  tiktok: { limit: 2200, tone: "energetic, creator-friendly, direct", format: "caption plus concise hook/CTA guidance for the video" },
  youtube: { limit: 5000, titleLimit: 100, tone: "search-aware, informative, compelling", format: "video description with a title suggestion, summary, CTA, and optional hashtags" },
};

type GeneratedVariant = {
  platform: AiPlatform;
  variation: number;
  title: string | null;
  caption: string;
  hashtags: string[];
  cta: string | null;
  media_recommendations: string[];
};

function cleanJsonText(value: string) {
  return value.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
}

function validateVariant(variant: GeneratedVariant) {
  const rules = PLATFORM_RULES[variant.platform];
  const captionLength = variant.caption.length;
  const titleLength = variant.title?.length ?? 0;
  return {
    character_count: captionLength,
    character_limit: rules.limit,
    title_character_count: titleLength,
    title_character_limit: rules.titleLimit ?? null,
    within_limit: captionLength <= rules.limit && (rules.titleLimit == null || titleLength <= rules.titleLimit),
    hashtag_count: variant.hashtags.length,
    warnings: [
      ...(captionLength > rules.limit ? [`Caption exceeds ${rules.limit} characters.`] : []),
      ...(rules.titleLimit != null && titleLength > rules.titleLimit ? [`Title exceeds ${rules.titleLimit} characters.`] : []),
    ],
  };
}

function buildPrompt(masterContent: string, platforms: AiPlatform[], brandVoice: string, instructions: string, variations: number) {
  const platformBlock = platforms.map((platform) => {
    const rules = PLATFORM_RULES[platform];
    return `${platform}: caption max ${rules.limit}; ${rules.titleLimit ? `title max ${rules.titleLimit}; ` : ""}${rules.tone}; ${rules.format}.`;
  }).join("\n");
  return `You are OmniSocial's platform-aware social content engine. Transform one master idea into native, publish-ready variants. Do not invent factual claims, statistics, prices, dates, offers, credentials, or product capabilities that are not in the master content. Preserve named entities and required facts exactly. Never mention that the text was generated by AI.

MASTER CONTENT:
${masterContent}

BRAND VOICE:
${brandVoice || "Clear, confident, natural, and audience-first."}

ADDITIONAL INSTRUCTIONS:
${instructions || "Keep the message faithful to the master content and optimize it for each platform."}

REQUESTED PLATFORMS:
${platformBlock}

Create ${variations} variation(s) per platform. Each variation must be materially different while preserving the same factual message. Return JSON only with this exact shape: {"variants":[{"platform":"instagram","variation":1,"title":null,"caption":"...","hashtags":["#..."],"cta":"...","media_recommendations":["..."]}]}. Include one object for every requested platform and variation number from 1 to ${variations}.`;
}

const RESPONSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    variants: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          platform: { type: "string", enum: AI_PLATFORMS },
          variation: { type: "integer" },
          title: { type: ["string", "null"] },
          caption: { type: "string" },
          hashtags: { type: "array", items: { type: "string" } },
          cta: { type: ["string", "null"] },
          media_recommendations: { type: "array", items: { type: "string" } },
        },
        required: ["platform", "variation", "title", "caption", "hashtags", "cta", "media_recommendations"],
      },
    },
  },
  required: ["variants"],
};

export async function generatePlatformContent(input: {
  profileId: string;
  masterContent: string;
  platforms: string[];
  brandVoice?: string;
  instructions?: string;
  variations?: number;
  requireApproval?: boolean;
}) {
  const apiKey = process.env.OPENAI_API_KEY?.trim();
  if (!apiKey) throw new Error("OPENAI_API_KEY is not configured.");
  const requested = [...new Set(input.platforms.map((value) => value.toLowerCase()))];
  const platforms = requested.filter((value): value is AiPlatform => (AI_PLATFORMS as readonly string[]).includes(value));
  if (!platforms.length) throw new Error("At least one supported platform is required.");
  if (platforms.length !== requested.length) throw new Error(`Unsupported AI content platform: ${requested.filter((value) => !platforms.includes(value as AiPlatform)).join(", ")}.`);
  const masterContent = input.masterContent.trim();
  if (!masterContent) throw new Error("Master content is required.");
  if (masterContent.length > 10000) throw new Error("Master content must be 10,000 characters or fewer.");
  const variations = Math.min(3, Math.max(1, Math.floor(input.variations ?? 1)));
  const model = process.env.OPENAI_CONTENT_MODEL?.trim() || "gpt-6-luna";
  const prompt = buildPrompt(masterContent, platforms, input.brandVoice?.trim() ?? "", input.instructions?.trim() ?? "", variations);

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model,
      store: false,
      input: prompt,
      text: { format: { type: "json_schema", name: "omnisocial_platform_content", strict: true, schema: RESPONSE_SCHEMA } },
    }),
    cache: "no-store",
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = typeof payload?.error?.message === "string" ? payload.error.message : "AI content generation failed.";
    throw new Error(message);
  }
  const outputText = typeof payload.output_text === "string"
    ? payload.output_text
    : payload.output?.flatMap((item: { content?: Array<{ type?: string; text?: string }> }) => item.content ?? []).find((item: { type?: string }) => item.type === "output_text")?.text;
  if (!outputText) throw new Error("AI provider returned no structured content.");
  let parsed: { variants?: GeneratedVariant[] };
  try { parsed = JSON.parse(cleanJsonText(outputText)); } catch { throw new Error("AI provider returned invalid structured content."); }
  const variants = (parsed.variants ?? []).filter((variant) => platforms.includes(variant.platform));
  if (!variants.length) throw new Error("AI provider returned no usable platform variants.");
  const normalized = variants.map((variant) => ({ ...variant, hashtags: variant.hashtags ?? [], media_recommendations: variant.media_recommendations ?? [], validation: validateVariant(variant) }));

  const admin = createAdminClient();
  const { data: profile } = await admin.from("socialmedia_profiles").select("workspace_id").eq("id", input.profileId).maybeSingle();
  const workspaceId = profile?.workspace_id ? String(profile.workspace_id) : null;
  const requiresApproval = Boolean(input.requireApproval);
  const { data: generation, error: generationError } = await admin.from("socialmedia_ai_generations").insert({ profile_id: input.profileId, workspace_id: workspaceId, master_content: masterContent, brand_voice: input.brandVoice?.trim() || null, instructions: input.instructions?.trim() || null, requested_platforms: platforms, model, provider: "openai", status: normalized.every((item) => item.validation.within_limit) ? "completed" : "partial", requires_approval: requiresApproval, result: { variants: normalized } }).select("id,created_at,status,model,requires_approval").single();
  if (generationError || !generation) throw new Error("Generated content could not be saved.");
  const rows = normalized.map((variant) => ({ generation_id: generation.id, profile_id: input.profileId, workspace_id: workspaceId, platform: variant.platform, caption: variant.caption, title: variant.title, hashtags: variant.hashtags, cta: variant.cta, media_recommendations: variant.media_recommendations, character_count: variant.validation.character_count, character_limit: variant.validation.character_limit, validation: variant.validation, variation: variant.variation, approval_status: requiresApproval ? "pending" : "approved" }));
  const { error: variantError } = await admin.from("socialmedia_ai_content_variants").insert(rows);
  if (variantError) throw new Error("Generated variants could not be saved.");
  return { generation: { ...generation, profile_id: input.profileId }, variants: normalized };
}

export async function getGeneration(profileId: string, generationId: string) {
  const admin = createAdminClient();
  const { data: generation, error } = await admin.from("socialmedia_ai_generations").select("id,master_content,brand_voice,instructions,requested_platforms,model,provider,status,requires_approval,approved_at,created_at,updated_at,error_message").eq("id", generationId).eq("profile_id", profileId).maybeSingle();
  if (error || !generation) return null;
  const { data: variants } = await admin.from("socialmedia_ai_content_variants").select("id,platform,variation,title,caption,hashtags,cta,media_recommendations,character_count,character_limit,validation,approval_status,created_at").eq("generation_id", generationId).eq("profile_id", profileId).order("platform").order("variation");
  return { generation, variants: variants ?? [] };
}

export async function approveGeneration(profileId: string, generationId: string, approvedBy: string) {
  const admin = createAdminClient();
  const { data: generation, error } = await admin.from("socialmedia_ai_generations").update({ status: "approved", approved_at: new Date().toISOString(), approved_by: approvedBy, updated_at: new Date().toISOString() }).eq("id", generationId).eq("profile_id", profileId).select("id,status,approved_at").maybeSingle();
  if (error || !generation) throw new Error("Generation not found.");
  const { error: variantsError } = await admin.from("socialmedia_ai_content_variants").update({ approval_status: "approved", updated_at: new Date().toISOString() }).eq("generation_id", generationId).eq("profile_id", profileId);
  if (variantsError) throw new Error("Unable to approve generated variants.");
  return generation;
}
